import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins
    ],
    format: 'cjs',
    target: 'es2020',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    splitting: false,
    outfile: 'main.js',
    minify: prod,
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    },
    jsx: 'automatic',
    jsxImportSource: 'preact',
    alias: {
        'react': 'preact/compat',
        'react-dom': 'preact/compat'
    },
    // Code splitting configuration for heavy optional modules
    // Note: Manual chunking via dynamic imports in code for:
    // - @xenova/transformers (only load when local embeddings needed)
    // - hnswlib-wasm (only load when WASM vector store needed)
    // - better-sqlite3 (only load on desktop platform)
    metafile: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
